spring:
  application:
  name: api-gateway

  cloud:
    gateway:
      discovery:
        enable: true
        lower-case-service-id: true

      routes:
        # User Service Routes
        - id: user-service-auth
          uri: lb://user-service
          predictates:
            - path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenish-rate: 10
                redif-rate-limiter.burst-capacity: 20

        - id: user-service
          uri: lb://user-service
          predictates:
            - Path=/users/**
          filters:
            - JwtAutenticationGateWayFilterFactory

        # Product Service Routes
        - id: product-service-public
          uri: lb://product-service
          predictates:
            - Path=/products
            - Method=Get

        - id: product-service-public-by-id
          uri: lb://product-service
          predictates:
            - Path=/products{id}
            - Method=Get

        - id: product-service-potected
          uri: lb://product-service
          predictates:
            - Path=/products/**
          filters:
            - JwtAutenticationGateWayFilterFactory

        # Media Service Routes
        - id: media-service
          uri: lb://media-service
          predictates:
            - Path=/media/**
          filters:
            - JwtAutenticationGateWayFilterFactory
            - name: RequestSize
              args:
                maxSize: 2MB

      default-filters:
        - DedupeResponseHeader=Acess-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
    endpoint:
      health:
        show-details: always

logging:
  level:
    org.sprinframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

application:
  security:
    jwt:
      security-key: mySecretKey
